/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: JspCServletContext/1.0
 * Generated at: 2012-08-22 06:56:59 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */

import java.io.IOException;

import javax.servlet.Servlet;
import javax.servlet.ServletConfig;
import javax.servlet.ServletException;
import javax.servlet.ServletRequest;
import javax.servlet.ServletResponse;

public final class CROSS_SITE_REQUEST_FORGERY_TestCase extends org.apache.jasper.runtime.HttpJspBase implements org.apache.jasper.runtime.JspSourceDependent, Servlet{
    private static final javax.servlet.jsp.JspFactory _jspxFactory=
            javax.servlet.jsp.JspFactory.getDefaultFactory();

    private static java.util.Map<java.lang.String, java.lang.Long> _jspx_dependants;

    private javax.el.ExpressionFactory _el_expressionfactory;
    private org.apache.tomcat.InstanceManager _jsp_instancemanager;

    public java.util.Map<java.lang.String, java.lang.Long> getDependants(){
        return _jspx_dependants;
    }

    public void _jspInit(){
        _el_expressionfactory=_jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        _jsp_instancemanager=org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
    }

    public void _jspDestroy(){
    }

    public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
            throws java.io.IOException, javax.servlet.ServletException{

        final javax.servlet.jsp.PageContext pageContext;
        javax.servlet.http.HttpSession session=null;
        final javax.servlet.ServletContext application;
        final javax.servlet.ServletConfig config;
        javax.servlet.jsp.JspWriter out=null;
        final java.lang.Object page=this;
        javax.servlet.jsp.JspWriter _jspx_out=null;
        javax.servlet.jsp.PageContext _jspx_page_context=null;


        try{
            response.setContentType("text/html;charset=euc-kr");
            pageContext=_jspxFactory.getPageContext(this, request, response,
                                                    null, true, 8192, true);
            _jspx_page_context=pageContext;
            application=pageContext.getServletContext();
            config=pageContext.getServletConfig();
            session=pageContext.getSession();
            out=pageContext.getOut();
            _jspx_out=out;

            out.write("\r\n");
            out.write("\r\n");
            out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
            out.write("<html> \r\n");
            out.write("<title>Excel Files</title>\r\n");
            out.write("<head>\r\n");
            out.write("<title>Untitled Document</title>\r\n");
            out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=euc-kr\">\r\n");
            out.write("<link href=\"../css/qmscbt.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
            out.write("</head>\r\n");
            out.write("<body leftmargin=\"0\" topmargin=\"0\">\r\n");
            out.write("\t<table width=\"561\"  border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
            out.write("<tr> \r\n");
            out.write("\t\t\t<td width=\"561\" height=\"48\" background=\"../images/230_pop_01.gif\"><img src=\"../images/362_pop_tit.gif\" width=\"110\" height=\"48\"></td>\r\n");
            out.write("\t  </tr>\r\n");
            out.write("\t\t<tr> \r\n");
            out.write("\t\t  <td valign=\"top\" style=\"padding:20 20 0 20\">\r\n");
            out.write("\t\t\t\t<table width=\"100%\"  border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
            out.write("\t\t\t\t\r\n");
            out.write("\t\t\t\t\t\r\n");
            out.write("                    <tr><td>\r\n");
            out.write("                    <table width=\"100%\" border=\"1\" cellpadding=\"0\" cellspacing=\"1\" bordercolor=\"#FFFFFF\" bgcolor=\"d0d0d0\">\r\n");
            out.write("                    <form name = testForm enctype =  \"multipart/form-data\" action='e < x >cel1.jsp'>\r\n");
            out.write("                    </form>\r\n");
            out.write("                    <form enctype=\"multipart/form-data\" action=");
            out.write("\"excel1.jsp\" meth");
            out.write("od=\"post\">\r\n");
            out.write("                    </form>\r\n");
            out.write("                    <form enctype='multipart/form-data' action=excel1.jsp method=\"Post\">\r\n");
            out.write("                    \r\n");
            out.write("                    <tr> <td width=\"150\" height=\"30\" align=\"center\" bgcolor=\"d0d0d0\">파일</td>\r\n");
            out.write("\t\t\t\t\t\t<td valign=\"top\" bgcolor=\"#FFFFFF\">\r\n");
            out.write("                      <input type=file name=\"userfile\">                        </td>\r\n");
            out.write("\t\t\t\t  </tr>\r\n");
            out.write("                    <tr> <td height=\"40\" colspan=\"2\" align=\"center\" bgcolor=\"#FFFFFF\">\r\n");
            out.write("                      <input type=submit value=\"등록\"><input type=button value=\"닫기\" onClick=\"window.close();\">\r\n");
            out.write("                      </td>\r\n");
            out.write("\t\t\t\t\t  </tr> \r\n");
            out.write("                      </form>\r\n");
            out.write("                      </table>                 \r\n");
            out.write("              \r\n");
            out.write("                      </td>\r\n");
            out.write("\t\t\t\t\t  </tr> \r\n");
            out.write("\t\t\t\t</table>\r\n");
            out.write("\t\t  </td>\r\n");
            out.write("\t\t</tr>\r\n");
            out.write("\t\t<tr>\r\n");
            out.write("\t\t\t<td height=\"10\" background=\"../images/230_pop_02.gif\"><img src=\"../images/space.gif\" width=\"1\" height=\"1\"></td>\r\n");
            out.write("\t\t</tr>\r\n");
            out.write("\t</table>\r\n");
            out.write("</body>\r\n");
            out.write("</html>");
        }catch(java.lang.Throwable t){
            if(!(t instanceof javax.servlet.jsp.SkipPageException)){
                out=_jspx_out;
                if(out!=null && out.getBufferSize()!=0)
                    try{ out.clearBuffer(); }catch(java.io.IOException e){}
                if(_jspx_page_context!=null) _jspx_page_context.handlePageException(t);
                else throw new ServletException(t);
            }
        }finally{
            _jspxFactory.releasePageContext(_jspx_page_context);
        }
    }

    @Override
    public void destroy() {
        // TODO Auto-generated method stub

    }

    @Override
    public ServletConfig getServletConfig() {
        // TODO Auto-generated method stub
        return null;
    }

    @Override
    public String getServletInfo() {
        // TODO Auto-generated method stub
        return null;
    }

    @Override
    public void init(ServletConfig arg0) throws ServletException {
        // TODO Auto-generated method stub

    }

    @Override
    public void service(ServletRequest arg0, ServletResponse arg1) throws ServletException, IOException {
        // TODO Auto-generated method stub

    }
}
